name: Build and Test MACS3 website using Sphinx

on: 
  push: 
    paths: 
      - 'docs/**'
      - '**.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Set up the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx myst-parser sphinx-rtd-theme # Add other dependencies you might have

    - name: Build Sphinx Documentation
      run: |
        cd docs  # Change to your documentation directory if needed
        make html
        cd ..

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './docs/build/html'

