# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MACS3 website using Jekyll

on: 
  push:
    paths:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy: 
      matrix: 
        python-version: [3.12]
        arch: ['x64']
    name: Build MACS3 website on x64 with Python ${{ matrix.python-version }}
    steps:
      - name: Checkout MACS
        uses: actions/checkout@v4
        #with: # we don't need submodules for building docs
        #  submodules: 'true'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install github-pages
        run: |
          gem install github-pages
      - name: Build the site in Jekyll
        run: |
          jekyll build --source docs --destination _site
      - name: Archive HTML files
        run: |
          zip -r site.zip ./_site
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jekyll-site
          path: site.zip
