# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MACS3 CI non x64

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/build-and-test-MACS3-non-x64.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/build-and-test-MACS3-non-x64.yml'

jobs:
  build_job:
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
          - arch: armv7
          - arch: ppc64le
          - arch: s390x

    steps:
      - name: Checkout MACS
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up arch and run
        uses: uraimo/run-on-arch-action@v2
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu22.04

          githubToken: ${{ github.token }}

          # The shell to run commands with in the container
          shell: /bin/bash

          # Mount the current working directory (with checked-out codes) as /MACS3 in the container
          dockerRunArgs: |
            -v "${PWD}:/MACS3" -u macs3

          # Create an artifacts directory on runner

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            useradd -m macs3
            mkdir -p /MACS3
            chown -R macs3:macs3 /MACS3
            # install dependencies
            apt-get update -qq -y
            apt-get install apt-utils
            apt-get install -yq bc libblas3 liblapack3 libblas-dev liblapack-dev
            # we rely on Debian/Ubuntu/Linux python packages for
            # numpy/scipy/sklearn
            # in Ubuntu 22
            #  numpy: 1.21.5
            #  scipy: 1.8.0
            #  sklearn: 0.23.2
            #  cython: 0.29.28
            apt-get install -yq python3 python3-pip python3-venv python3-wheel python3-numpy python3-scipy python3-sklearn cython3 
            apt-get install -yq procps zlib1g zlib1g-dev gfortran
          run: |
            echo `uname -a`
            cd /home/macs3/
            
            # let's create virtualenv
            python3 -m venv --system-site-packages macsenv

            # activate macsenv
            source macsenv/bin/activate
            
            # copy source code over
            cp -r /MACS3 .
            cd MACS3

            # let's make sure this file is gone...
            rm -f no-global-site-packages.txt

            # pip will be upgraded
            python3 -m pip install --upgrade pip

            # since we require Cython3, cython will be upgraded to
            # version > 3.0
            # --upgrade-strategy only-if-needed flag is used so that
            # we only upgrade libs if necessary. In this case, Cython,
            # Numpy, setuptools will be upgraded.
            if [ -f requirements.txt ]; then
              pip3 install --upgrade-strategy only-if-needed -r requirements.txt;
            fi

            # install MACS3; only-if-needed won't try to upgrade Debian/Linux python3 libs
            # pip install --upgrade-strategy only-if-needed
            # --no-build-isolation --progress-bar off .

            # Because we already upgraded the libraries in previous
            # step, I don't expect to see any dependencies will be
            # upgraded here.
            pip3 install --upgrade-strategy only-if-needed --no-build-isolation .
            # run test
            pytest --runxfail && cd test && ./cmdlinetest macs3

            # copy testing results from cmdlinetest over
            cp -r ../temp /MACS3/

      - name: Archive cmdlinetest results
        uses: actions/upload-artifact@v3
        with:
          name: cmdlinetest results
          path: |
            temp/
