# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MACS3 CI x64

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/build-and-test-MACS3-x64.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/build-and-test-MACS3-x64.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy: 
      matrix: 
        python-version: ["3.11"]
        arch: ['x64']
    name: Build on x64 with Python ${{ matrix.python-version }}
    steps:
      - name: Checkout MACS
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-        
      - name: Install dependencies
        run: |
          # make sure pip is the lastest
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi
      - name: Install MACS
        run: |
          # we use pip install instead of old fashion setup.py install
          pip install .
      - name: Test with pytest
        run: |
          pytest --runxfail
          cd test
          ./cmdlinetest macs3
          cd ..
      - name: Build sdist
        run: |
          python setup.py sdist
      - name: Archive sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-${{ matrix.arch }}-${{ matrix.python-version }}
          path: |
            dist/*.tar.gz

