name: Build and Test MACS3 website using Sphinx

on: 
  push: 
    paths: 
      - 'docs/**'
      - '.github/workflows/build-and-test-MACS3-website.yml'

  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx myst-parser sphinx-rtd-theme

    - name: Build Sphinx Documentation
      run: |
        cd docs
        make html
        cd ..

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Archive and upload entire website
        path: './docs/build/html'

